{
 "title": "bcachefs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(bcachefs_dev_capacity,instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(bcachefs_dev_capacity,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$disk",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bcachefs_dev_alloc_bytes{device=~\"$disk.+\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "bcachefs_dev_capacity{device=~\"$disk.+\"}",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval])",
     "legendFormat": "IO"
    },
    {
     "expr": "irate(node_disk_discard_time_seconds_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval])",
     "legendFormat": "discard"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$host:9100\", device=\"$disk\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  }
 ]
}